spring:
  profiles:
    active: release

  cache:
    jcache:
      config: classpath:ehcache.xml

#sample006_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#sample007_h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # < tcp(You can save permanently) | inmemory(Temporarily save) > jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#sample008_jpa
  jpa:
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Query engine setting
        format_sql: true
        use_sql_comments: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        sql: trace

springdoc:
  api-docs:
    path: /api-docs # 접속 path 설정
    group:
      enabled: true
  swagger-ui:
    path: /swagger-ui # 접속 path 설정
    enabled: true
    group-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    doc-expansion: none
  cache:
    disabled: true # swagger cache 설정
  model-and-view-allowed: true