spring:
  profiles:
    active: release

  cache:
    jcache:
      config: classpath:ehcache.xml

#sample006_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest