spring:
  profiles:
    active: release

  cache:
    jcache:
      config: classpath:ehcache.xml

#sample006_rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#sample007_h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # < tcp(You can save permanently) | inmemory(Temporarily save) > jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

